# finally 

finally块总是当try块退出执行。这确保了即使是在执行中发生了异常，finally也会执行。但它不仅仅是处理异常，还避免了你不小心绕过了一些资源清除的代码。比如 return, continue, or break.的时候。这往往是非常有用的

但最终不仅仅是异常处理是有用的——它允许程序员避免清除代码不小心绕过热土,继续,或休息。将在finally块中清理代码总是一个很好的实践,即使不预期的异常。